---
title: "02-RNA-seq"
author: "Claudia-Halibut"
format: html
editor: visual
---

4/9/2025 Objective: Installing Kallisto and running DESeq2

```{r, engine='bash'}
## the following code downloads and runs the kallisto software

/home/shared/kallisto/kallisto

## "include = FALSE" prevents code and results from appearing in the finished file. R Markdown still runs the code in the chunk, and the results can be used by other chunks.
```

```{bash}
## check working directory, change the directory to the data folder because the computer may not always do it, and re-check the directory
#NOTE: typed in bash because I just did not want to change to R since this a trivial part of the code

pwd
cd data/
pwd 
```

```{r pull, engine='bash'}
## the following code downloads the Pacific oyster fasta file of genes and does so ignoring the fact that gannet does not have a security certificate to authenticate via 'insecure'
#NOTE: pull the data from URL

cd data/
curl --insecure -O https://gannet.fish.washington.edu/seashell/bu-github/nb-2023/Cgigas/data/rna.fna
```

```{r kallisto, engine='bash'}
## calling on the _rna file for indexing and renaming it under solely "rna.fna"

/home/shared/kallisto/kallisto \
index -i \
data/cgigas_roslin_rna.index \
data/rna.fna
```

```{r pull, engine='bash'}
## the following code will download the sequence reads from the attached URL while allowing: recursive downloading, no grab directories aside from desired, and specifies a comma-separated list of file extensions

cd data 
wget --recursive --no-parent --no-directories \
--no-check-certificate \
--accept '*.fastq.gz' \
https://gannet.fish.washington.edu/seashell/bu-github/nb-2023/Cgigas/data/nopp/
```

```{bash}
## re-check directory and print output

pwd
```

```{r kallisto, engine='bash'}
## the following code will: change the directory to ensure that it is set, go backwards to create a new directory under assignments, find files, remove L001 file, runs quant() function on each, locates index file to align files, writes to designated output file in created sub-directory, 40 threads for computation (chromosome recognition?), and specify the input file has single-end reads with SD of 10
#NOTE: double check to make sure files are routed correctly

cd data #changing the directory just makes it easier so I do not get confused
mkdir -o ../output/kallisto_01

find ../data/*fastq.gz \
| xargs basename -s _L001_R1_001.fastq.gz | xargs -I{} /home/shared/kallisto/kallisto \
quant -i ../data/cgigas_roslin_rna.index \
-o ../output/kallisto_01/{} \
-t 40 \
--single -l 100 -s 10 ../data/{}_L001_R1_001.fastq.gz
```

```{r kallisto, engine='bash'}
## runs the abundance_estimates_to_matrix.pl script from the Trinity RNA-seq assembly software package to create a gene expression matrix from kallisto output files
#NOTE: Use ../output/kallisto_01 as the output directory and prefix for the gene expression matrix file

cd data 
perl /home/shared/trinityrnaseq-v2.12.0/util/abundance_estimates_to_matrix.pl \
--est_method kallisto \
    --gene_trans_map none \
    --out_prefix ../output/kallisto_01 \
    --name_sample_by_basedir \
    ../output/kallisto_01/D54_S145/abundance.tsv \
    ../output/kallisto_01/D56_S136/abundance.tsv \
    ../output/kallisto_01/D58_S144/abundance.tsv \
    ../output/kallisto_01/M45_S140/abundance.tsv \
    ../output/kallisto_01/M48_S137/abundance.tsv \
    ../output/kallisto_01/M89_S138/abundance.tsv \
    ../output/kallisto_01/D55_S146/abundance.tsv \
    ../output/kallisto_01/D57_S143/abundance.tsv \
    ../output/kallisto_01/D59_S142/abundance.tsv \
    ../output/kallisto_01/M46_S141/abundance.tsv \
    ../output/kallisto_01/M49_S139/abundance.tsv \
    ../output/kallisto_01/M90_S147/abundance.tsv \
    ../output/kallisto_01/N48_S194/abundance.tsv \
    ../output/kallisto_01/N50_S187/abundance.tsv \
    ../output/kallisto_01/N52_S184/abundance.tsv \
    ../output/kallisto_01/N54_S193/abundance.tsv \
    ../output/kallisto_01/N56_S192/abundance.tsv \
    ../output/kallisto_01/N58_S195/abundance.tsv \
    ../output/kallisto_01/N49_S185/abundance.tsv \
    ../output/kallisto_01/N51_S186/abundance.tsv \
    ../output/kallisto_01/N53_S188/abundance.tsv \
    ../output/kallisto_01/N55_S190/abundance.tsv \
    ../output/kallisto_01/N57_S191/abundance.tsv \
    ../output/kallisto_01/N59_S189/abundance.tsv
```

```{r}
## load and install necessary packages and rearrange some lines because it would not run properly originally

BiocManager::install("DESeq2")
library(DESeq2)
library(tidyverse)
install.packages("RColorBrewer")
install.packages("pheatmap")
library(pheatmap)
library(RColorBrewer)
library(data.table)
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
```

```{r}
## double check directory 

getwd()
```

```{r}
## read in the count matrix (cell-by-gene matrix where each cell entry represents the number of RNA reads)
#NOTE: matrix is data structure in single-cell RNA sequencing (RNA-Seq)

setwd("~/Claudia-Halibut/assignments /output")

countmatrix <- read.delim("../output/kallisto_01.isoform.counts.matrix", header = TRUE, sep = '\t')
rownames(countmatrix) <- countmatrix$X
countmatrix <- countmatrix[,-1]
head(countmatrix)
```

```{r}
## round integers up to whole numbers for further analysis:
#NOTE: 73,307 observations, but could differ with another run

countmatrix <- round(countmatrix, 0)
str(countmatrix)
```

```{r}
## get DEGs (Differentially Expressed Gene) based on Desication
#NOTE: the function DESeqData..(), will not run without being in the same block as DESeq2 library. 

BiocManager::install("DESeq2")
library(DESeq2)

deseq2.colData <- data.frame(condition=factor(c(rep("control", 12), rep("desicated", 12))), 
                             type=factor(rep("single-read", 24)))
rownames(deseq2.colData) <- colnames(data)
deseq2.dds <- DESeqDataSetFromMatrix(countData = countmatrix,
                                     colData = deseq2.colData, 
                                     design = ~ condition)

deseq2.dds <- DESeq(deseq2.dds)
deseq2.res <- results(deseq2.dds)
deseq2.res <- deseq2.res[order(rownames(deseq2.res)), ]

head(deseq2.res)
dim(deseq2.res[!is.na(deseq2.res$padj) & deseq2.res$padj <= 0.05, ])
```

```{r}
## added to the above code block because it will not run otherwise

#deseq2.dds <- DESeq(deseq2.dds)
#deseq2.res <- results(deseq2.dds)
#deseq2.res <- deseq2.res[order(rownames(deseq2.res)), ]
```

```{r}
## head function returns the first part of the binary resource file. A continuation of getting the DEGs (Differentially Expressed Gene) based on Desication
#NOTE: as of 5/25/2025 I added this code to the above code chunk to check if it functions better with the rest of the code 

head(deseq2.res)
```

```{r}
## count number of hits with adjusted p-value less then 0.05
#NOTE: RESULTS 607 condition desicated against 6 controls?? 
#NOTE: as of 5/25/2025 I added this code to the above code chunk

dim(deseq2.res[!is.na(deseq2.res$padj) & deseq2.res$padj <= 0.05, ])
```

```{r}
## provides with visulaized plot 

tmp <- deseq2.res
# The main plot
plot(tmp$baseMean, tmp$log2FoldChange, pch=20, cex=0.45, ylim=c(-3, 3), log="x", col="darkgray",
     main="DEG Dessication  (pval <= 0.05)",
     xlab="mean of normalized counts",
     ylab="Log2 Fold Change")
# Getting the significant points and plotting them again so they're a different color
tmp.sig <- deseq2.res[!is.na(deseq2.res$padj) & deseq2.res$padj <= 0.05, ]
points(tmp.sig$baseMean, tmp.sig$log2FoldChange, pch=20, cex=0.45, col="red")
# 2 FC lines
abline(h=c(-1,1), col="blue")
```

```{r}
## successfully send file to output DEGlist

setwd("~/Claudia-Halibut/assignments /output")
write.table(tmp.sig, "output/DEGlist.tab", row.names = T)
```
