---
title: "07-CG-Motifs"
format: html
editor: visual
---

```{bash}
## as of 6/12/2025 the chunks are running but their are issues with the fastq file load. Moving on temporarily because I lack a fasta file to input and the fastq file is throwing issues
```

```{bash}
## check the working directory
pwd
```

```{r}
# Load necessary libraries
library(ShortRead)
install.packages("BiocManager")
BiocManager::install("ShortRead")
install.packages("seqinr")
library(seqinr)

# Define input and output file paths
input_file <- "../project/trimgalore-out/E2_T2_F1_val_2.fq.gz"
output_fasta <- "../output/selected_sequences.fasta"
#sequences <- read.fasta(input_file)

# Read the entire FASTQ file
fq <- readFastq(input_file)

# Set seed for reproducibility
set.seed(42)

# Define number of sequences to select
number_of_sequences_to_select <- 10

# Check if there are enough sequences
if (length(sequences) < number_of_sequences_to_select) {
  warning("There are fewer than 10 sequences in the FASTQ file. All sequences will be selected.")
  number_of_sequences_to_select <- length(fq)
}

# Sample sequences
selected_indices <- sample(length(fq), number_of_sequences_to_select)
selected_sequences <- fq[selected_indices]

# Write selected sequences to a FASTA file
writeFasta(sread(selected_sequences), file = output_fasta)
```

```{r}
## replace 'output.fasta' with your desired output file name -- replaced with E2outf10.fasta
#NOTE: cannot test if file functions

output_f <- "output/E2outf10.fasta"
write.fasta(selected_sequences, names(selected_sequences), output_f, open = "w")
tail -2 output/E2outf10.fasta
```

```{bash}
#likely will not need; fix issue where gff and fa name did not match
# sed -i 's/>lcl|/>/g' ../output/10_seqs.fa
```

```{bash}
## needed downstream for IGV -still need to figure out the godforsaken IGV

/home/shared/samtools-1.12/samtools faidx \
output/10_seqs.fa
```

```{bash}
## reads nucleotide sequences 

fuzznuc -sequence output/10_seqs.fa -pattern CG -rformat gff -outfile output/CGoutput.gff
```
